package com.dcdy.vote.dao;

import com.dcdy.vote.dao.VtBoard;
import com.dcdy.vote.dao.VtBoardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VtBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int countByExample(VtBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int deleteByExample(VtBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int deleteByPrimaryKey(String vtKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int insert(VtBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int insertSelective(VtBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    List<VtBoard> selectByExample(VtBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    VtBoard selectByPrimaryKey(String vtKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") VtBoard record, @Param("example") VtBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByExample(@Param("record") VtBoard record, @Param("example") VtBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByPrimaryKeySelective(VtBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByPrimaryKey(VtBoard record);
}