package com.dcdy.vote.dao;

import java.util.ArrayList;
import java.util.List;

public class VtBoardExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public VtBoardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVtKeyIsNull() {
            addCriterion("vt_key is null");
            return (Criteria) this;
        }

        public Criteria andVtKeyIsNotNull() {
            addCriterion("vt_key is not null");
            return (Criteria) this;
        }

        public Criteria andVtKeyEqualTo(String value) {
            addCriterion("vt_key =", value, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyNotEqualTo(String value) {
            addCriterion("vt_key <>", value, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyGreaterThan(String value) {
            addCriterion("vt_key >", value, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyGreaterThanOrEqualTo(String value) {
            addCriterion("vt_key >=", value, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyLessThan(String value) {
            addCriterion("vt_key <", value, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyLessThanOrEqualTo(String value) {
            addCriterion("vt_key <=", value, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyLike(String value) {
            addCriterion("vt_key like", value, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyNotLike(String value) {
            addCriterion("vt_key not like", value, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyIn(List<String> values) {
            addCriterion("vt_key in", values, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyNotIn(List<String> values) {
            addCriterion("vt_key not in", values, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyBetween(String value1, String value2) {
            addCriterion("vt_key between", value1, value2, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtKeyNotBetween(String value1, String value2) {
            addCriterion("vt_key not between", value1, value2, "vtKey");
            return (Criteria) this;
        }

        public Criteria andVtValIsNull() {
            addCriterion("vt_val is null");
            return (Criteria) this;
        }

        public Criteria andVtValIsNotNull() {
            addCriterion("vt_val is not null");
            return (Criteria) this;
        }

        public Criteria andVtValEqualTo(String value) {
            addCriterion("vt_val =", value, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValNotEqualTo(String value) {
            addCriterion("vt_val <>", value, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValGreaterThan(String value) {
            addCriterion("vt_val >", value, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValGreaterThanOrEqualTo(String value) {
            addCriterion("vt_val >=", value, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValLessThan(String value) {
            addCriterion("vt_val <", value, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValLessThanOrEqualTo(String value) {
            addCriterion("vt_val <=", value, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValLike(String value) {
            addCriterion("vt_val like", value, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValNotLike(String value) {
            addCriterion("vt_val not like", value, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValIn(List<String> values) {
            addCriterion("vt_val in", values, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValNotIn(List<String> values) {
            addCriterion("vt_val not in", values, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValBetween(String value1, String value2) {
            addCriterion("vt_val between", value1, value2, "vtVal");
            return (Criteria) this;
        }

        public Criteria andVtValNotBetween(String value1, String value2) {
            addCriterion("vt_val not between", value1, value2, "vtVal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vt_board
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 21 19:55:12 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}