package com.dcdy.vote.dao;

import java.io.Serializable;

public class VtBoard implements Serializable {
    /**
     *
     */
    private String vtKey;

    /**
     *
     */
    private String vtVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vt_board
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     */
    public String getVtKey() {
        return vtKey;
    }

    /**
     *
     */
    public void setVtKey(String vtKey) {
        this.vtKey = vtKey == null ? null : vtKey.trim();
    }

    /**
     *
     */
    public String getVtVal() {
        return vtVal;
    }

    /**
     *
     */
    public void setVtVal(String vtVal) {
        this.vtVal = vtVal == null ? null : vtVal.trim();
    }
}