package com.dcdy.vote.dao;

import com.dcdy.vote.dao.VtCategory;
import com.dcdy.vote.dao.VtCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VtCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int countByExample(VtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int deleteByExample(VtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int insert(VtCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int insertSelective(VtCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    List<VtCategory> selectByExample(VtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    VtCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") VtCategory record, @Param("example") VtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByExample(@Param("record") VtCategory record, @Param("example") VtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByPrimaryKeySelective(VtCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByPrimaryKey(VtCategory record);
}