package com.dcdy.vote.dao;

import java.io.Serializable;

public class VtCategory implements Serializable {
    /**
     *流水号
     */
    private Integer id;

    /**
     *类目名称
     */
    private String categoryName;

    /**
     *图片地址
     */
    private String categoryImage;

    /**
     *投票数
     */
    private Integer voteNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vt_category
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *流水号
     */
    public Integer getId() {
        return id;
    }

    /**
     *流水号
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *类目名称
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     *类目名称
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     *图片地址
     */
    public String getCategoryImage() {
        return categoryImage;
    }

    /**
     *图片地址
     */
    public void setCategoryImage(String categoryImage) {
        this.categoryImage = categoryImage == null ? null : categoryImage.trim();
    }

    /**
     *投票数
     */
    public Integer getVoteNum() {
        return voteNum;
    }

    /**
     *投票数
     */
    public void setVoteNum(Integer voteNum) {
        this.voteNum = voteNum;
    }
}