package com.dcdy.vote.dao;

import java.io.Serializable;

public class VtCompany implements Serializable {
    /**
     *流水号
     */
    private Integer id;

    /**
     *单位名称
     */
    private String companyName;

    /**
     *类目编号
     */
    private Integer categoryId;

    /**
     *投票数量
     */
    private Integer voteNum;

    /**
     *单位图片
     */
    private String companyImage;

    /**
     *0未生效1已生效
     */
    private Integer status;

    /**
     *联系人名称
     */
    private String concatName;

    /**
     *联系人手机号
     */
    private String concatMobile;

    /**
     *名次
     */
    private Integer position;

    /**
     *客户端编号
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *流水号
     */
    public Integer getId() {
        return id;
    }

    /**
     *流水号
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *单位名称
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     *单位名称
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     *类目编号
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     *类目编号
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     *投票数量
     */
    public Integer getVoteNum() {
        return voteNum;
    }

    /**
     *投票数量
     */
    public void setVoteNum(Integer voteNum) {
        this.voteNum = voteNum;
    }

    /**
     *单位图片
     */
    public String getCompanyImage() {
        return companyImage;
    }

    /**
     *单位图片
     */
    public void setCompanyImage(String companyImage) {
        this.companyImage = companyImage == null ? null : companyImage.trim();
    }

    /**
     *0未生效1已生效
     */
    public Integer getStatus() {
        return status;
    }

    /**
     *0未生效1已生效
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     *联系人名称
     */
    public String getConcatName() {
        return concatName;
    }

    /**
     *联系人名称
     */
    public void setConcatName(String concatName) {
        this.concatName = concatName == null ? null : concatName.trim();
    }

    /**
     *联系人手机号
     */
    public String getConcatMobile() {
        return concatMobile;
    }

    /**
     *联系人手机号
     */
    public void setConcatMobile(String concatMobile) {
        this.concatMobile = concatMobile == null ? null : concatMobile.trim();
    }

    /**
     *名次
     */
    public Integer getPosition() {
        return position;
    }

    /**
     *名次
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     *客户端编号
     */
    public String getClientId() {
        return clientId;
    }

    /**
     *客户端编号
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }
}