package com.dcdy.vote.dao;

import com.dcdy.vote.dao.VtCompany;
import com.dcdy.vote.dao.VtCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VtCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int countByExample(VtCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int deleteByExample(VtCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int insert(VtCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int insertSelective(VtCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    List<VtCompany> selectByExample(VtCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    VtCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") VtCompany record, @Param("example") VtCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByExample(@Param("record") VtCompany record, @Param("example") VtCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByPrimaryKeySelective(VtCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_company
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByPrimaryKey(VtCompany record);
}