package com.dcdy.vote.dao;

import com.dcdy.vote.dao.VtVoteLog;
import com.dcdy.vote.dao.VtVoteLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VtVoteLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int countByExample(VtVoteLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int deleteByExample(VtVoteLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int insert(VtVoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int insertSelective(VtVoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    List<VtVoteLog> selectByExample(VtVoteLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    VtVoteLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") VtVoteLog record, @Param("example") VtVoteLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByExample(@Param("record") VtVoteLog record, @Param("example") VtVoteLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByPrimaryKeySelective(VtVoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    int updateByPrimaryKey(VtVoteLog record);
}