package com.dcdy.vote.dao;

import java.io.Serializable;
import java.util.Date;

public class VtVoteLog implements Serializable {
    /**
     *流水号
     */
    private Integer id;

    /**
     *客户端编号
     */
    private String clientId;

    /**
     *单位编号
     */
    private Integer companyId;

    /**
     *创建时间
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vt_vote_log
     *
     * @mbggenerated Mon Nov 21 19:55:12 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *流水号
     */
    public Integer getId() {
        return id;
    }

    /**
     *流水号
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *客户端编号
     */
    public String getClientId() {
        return clientId;
    }

    /**
     *客户端编号
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     *单位编号
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     *单位编号
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     *创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}